merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/added/', views.band_added, name='band-added'),
    path('bands/<int:id>/update/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
    path('contact/', views.contact, name='contact'),
    path('email-sent', views.email_sent, name='email-sent')
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        ROCK = "RK"
        JAZZ = 'JZ'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORDS = 'Records'
        CLOTHING = 'Clothing'
        POSTERS = 'Posters'
        MISCELLANEOUS = 'Misc'


    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        default=1900,
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    type = models.fields.CharField(choices=ListingType.choices, max_length=15)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.title}'

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__' (commented out instead of deleted)
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ('sold',)

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from listings.models import Band, Listing
from listings.forms import BandForm, ListingForm, ContactUsForm


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, 'listings/band_detail.html', {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)

        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request, 'listings/band_create.html', {'form': form})


def band_added(request):
    return render(request, 'listings/band_added.html')


def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)

    else:
        form = BandForm(instance=band)

    return render(request, 'listings/band_update.html', {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')

    return render(request, 'listings/band_delete.html', {'band': band})


def about(request):
    return render(request, 'listings/about.html')


def listing_list(request):
    all_listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings': all_listings})


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 'listings/listing_detail.html', {'listing': listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)

        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(request, 'listings/listing_create.html', {'form': form})


def listing_update(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing.id)

    else:
        form = ListingForm(instance=listing)

    return render(request, 'listings/listing_update.html', {'form': form})


def listing_delete(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')

    return render(request, 'listings/listing_delete.html', {'listing': listing})


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(subject=f'Message from {form.cleaned_data["name"] or "anonymous"} via MerchEx contact form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'])
            return redirect('email-sent')
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {'form': form})


def email_sent(request):
    return render(request, 'listings/email-sent.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Who we are</h1>

{% endblock %}

merchex/listings/templates/listings/band_added.html
{% extends 'listings/base.html' %}

{% block content %}

    <p>You have successfully added {{ band.name }} to our database.</p>
    <p><a href="{% url 'band-detail' band.id %}">View {{ band.name }} page</a></p>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Delete band</h1>
    <p>Are you sure you want to delete band {{ band.name }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete this band">
    </form>
    <a href="{% url 'band-detail' band.id %}">No, take me back to the page of {{ band.name }}</a>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

    <h2>{{ band.name }}</h2>

    <ul>
        <li>Genre: {{ band.get_genre_display }}</li>
        <li>Year formed: {{ band.year_formed }}</li>
        <li>Active: {{ band.active|yesno }}</li>
        {% if band.official_homepage %}
        <li><a href="{{ band.official_homepage }}" target="_blank">{{ band.official_homepage }}</a></li>
        {% endif %}
    </ul>

    <p>{{ band.biography }}</p>

    <div class="listings-grid">
        {% for listing in band.listing_set.all %}
            <div class="listing-item">
                <div class="listing-title">{{ listing.title }}</div>
                <div class="listing-type">{{ listing.type }}</div>
            </div>
        {% endfor %}
    </div>

    <a href="{% url 'band-update' band.id %}">Edit this Band</a>
    <a href="{% url 'band-delete' band.id %}">Delete this band</a>
    <a href="{% url 'band-list' %}">View all bands</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Bands</h1>
<p>The band you have in mind is not in the list?</p>
<p>Click <a href="{% url 'band-create' %}">here</a> to add a new band.</p>
<ul>
    {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
            - <span class="edit"><a href="{% url 'band-update' band.id %}">[edit]</span></a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

    <p>Modify band details</p>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

merchex/listings/templates/listings/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>
<body>
    <nav>
        <a href="{% url 'band-list' %}">Bands</a>
        <a href="{% url 'listing-list' %}">Listings</a>
        <a href="{% url 'contact' %}">Contact</a>
    </nav>
    {% block content %}{% endblock %}

</body>
</html>

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Hello Django!</h1>
<p>My favorite bands are:</p>
<ul>
    {% for band in bands %}
        <li>{{ band.name }}</li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

    <p>Add a new listing</p>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Delete listing</h1>
    <p>Are you sure you want to delete listing {{ listing.title }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete this listing">
    </form>
    <a href="{% url 'listing-detail' listing.id %}">No, take me back to the page of {{ listing.title }}</a>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

    <h2>{{ listing.title }}</h2>

    <ul>
        <li>Description: {{ listing.description }}</li>
        <li>Year: {{ listing.year }}</li>
        <li>Sold: {{ listing.sold|yesno }}</li>
        <li>Type: {{ listing.type }}</li>
        <li>Band: <a href="{% url 'band-detail' listing.band.id %}">{{ listing.band }}</a></li>
    </ul>

<a href="{% url 'listing-update' listing.id %}">Edit this listing</a>
<a href="{% url 'listing-delete' listing.id %}">Delete this listing</a>
<a href="{% url 'listing-list' %}">View all listings</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Listings</h1>
    <div id="create-new-listing">
        <p><a href="{% url 'listing-create' %}">Create a new listing</a></p>
    </div>
    <div class="listings-grid">
        {% for listing in listings %}
            <div class="listing-item">
                <div class="listing-title">
                    <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
                </div>
                <div class="listing-type">
                    {{ listing.type }}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

    <p>Modify your listing.</p>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Here are the listings</h1>
    <div id="test-header">
        <p></p>
    </div>
    <div id="listings-grid">
        {% for listing in listings %}
            <div class="listing-item">{{ listing.title }}</div>
        {% endfor %}
    </div>

{% endblock %}